# Generated by Django 4.2 on 2023-04-30 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.eventcategory'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_Date_Time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
