# Generated by Django 4.2 on 2023-05-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_eventcertificate_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='certificate',
        ),
        migrations.AddField(
            model_name='quiz',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.event'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='eventCategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.eventcategory'),
        ),
    ]
