# Generated by Django 4.2 on 2023-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0006_remove_quiz_certificate_quiz_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cpd_approval_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cpd_org_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
