# Generated by Django 4.2 on 2023-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0007_event_cpd_approval_no_event_cpd_org_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
