# Generated by Django 4.2 on 2023-05-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_alter_eventparticipant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_number',
        ),
    ]
