# Generated by Django 4.2 on 2023-05-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0011_alter_event_accreditation_no_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
